/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Component;
import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JOptionPane;
import model.User;


/**
 *
 * @author ProBook
 */
public class mainjframe extends javax.swing.JFrame {

    /**
     * Creates new form mainjframe
     */
    public mainjframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Userprofile = new javax.swing.JLabel();
        firstNametextfield = new javax.swing.JTextField();
        Firstname = new javax.swing.JLabel();
        Lastname = new javax.swing.JLabel();
        lastNametextfield = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        agetextfield = new javax.swing.JTextField();
        phonenumber = new javax.swing.JLabel();
        phonetextfieldbutton = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailtextfieldbutton = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        genderComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbiesTextArea = new javax.swing.JTextArea();
        hobbiesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        Userprofile.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Userprofile.setText("Create  a profile");

        firstNametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNametextfieldActionPerformed(evt);
            }
        });

        Firstname.setText("First Name");

        Lastname.setText("Last Name");

        gender.setText("Gender");

        age.setText("Age");

        phonenumber.setText("Phone Number");

        phonetextfieldbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetextfieldbuttonActionPerformed(evt);
            }
        });

        email.setText("Email");

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);

        hobbiesTextArea.setColumns(20);
        hobbiesTextArea.setRows(5);
        jScrollPane1.setViewportView(hobbiesTextArea);

        hobbiesLabel.setText("Hobbies");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitbutton)
                .addGap(265, 265, 265))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(agetextfield, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNametextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(firstNametextfield, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phonetextfieldbutton, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Firstname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lastname)
                    .addComponent(lastNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonetextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbiesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitbutton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonetextfieldbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetextfieldbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetextfieldbuttonActionPerformed

    private void firstNametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNametextfieldActionPerformed
 
        
    }//GEN-LAST:event_firstNametextfieldActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
        try {
        User userObject = new User();
        
        
        //name = this.firstNametextfield.getText().trim();
        userObject.setName(this.firstNametextfield.getText().trim());
        //lastname = this.lastNametextfield.getText().trim();
        userObject.setLastname(this.lastNametextfield.getText().trim());
        //gender = this.genderComboBox.getSelectedItem().toString();
        userObject.setGender(this.genderComboBox.getSelectedItem().toString());
        //hobbies = this.hobbiesTextArea.getText();
        userObject.setHobbies(this.hobbiesTextArea.getText());
        
        //age = Integer.parseInt(this.agetextfield.getText().trim());
        userObject.setAge(Integer.parseInt(this.agetextfield.getText().trim()));
        //phonenumber = Integer.parseInt(this.phonetextfieldbutton.getText().trim());
        userObject.setPhonenumber(Integer.parseInt(this.phonetextfieldbutton.getText().trim()));
        //email = this.emailtextfieldbutton.getText().trim();
        userObject.setEmail(this.emailtextfieldbutton.getText().trim());
        
        System.out.println(userObject.getName());
        System.out.println(userObject.getLastname());
        System.out.println(userObject.getGender());
        System.out.println(userObject.getAge());
        System.out.println(userObject.getPhonenumber());
        System.out.println(userObject.getEmail());
        System.out.println(userObject.getHobbies());
        System.out.println(userObject);
        
        
        
        if (userObject.getName().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your first name", "Oops", HEIGHT);
        } else if (userObject.getLastname().isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your last name", "Oops", HEIGHT);
        } else if (userObject.getGender().isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Please select your gender", "Oops", HEIGHT);
        } else if (agetextfield.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your age", "Oops", HEIGHT);
        } else if (phonetextfieldbutton.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your phone number", "Oops", HEIGHT);
        } else if (userObject.getEmail().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your email", "Oops", HEIGHT);
            
        } else if (userObject.getHobbies() .isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your hobbies", "Oops", HEIGHT);
        } else {
            JOptionPane.showMessageDialog(rootPane, 
            "Name: " + userObject.getName() + "\n" +
            "Last Name: " + userObject.getLastname() + "\n" +
            "Gender: " + userObject.getGender() + "\n" +
            "Age: " + userObject.getAge() + "\n" +
            "Phone Number: " + userObject.getPhonenumber() + "\n" +
            "Email: " + userObject.getEmail() + "\n" +
            "Hobbies: " + userObject.getHobbies(), 
            "Success!", 
            HEIGHT);

        }    
    } catch (NullPointerException ne) {
        JOptionPane.showMessageDialog(rootPane, "Please enter details above", "Oops!", HEIGHT);
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(rootPane, "Please enter valid number for age and phone", "Oops", HEIGHT);
    } catch (HeadlessException ex) {
        JOptionPane.showMessageDialog(rootPane, "An expected error occured:" + ex.getMessage(), "Error", HEIGHT);
    }//GEN-LAST:event_submitbuttonActionPerformed
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainjframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Firstname;
    private javax.swing.JLabel Lastname;
    private javax.swing.JLabel Userprofile;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtextfieldbutton;
    private javax.swing.JTextField firstNametextfield;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JTextArea hobbiesTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNametextfield;
    private javax.swing.JLabel phonenumber;
    private javax.swing.JTextField phonetextfieldbutton;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
