/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Component;
import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author ProBook
 */
public class mainjframe extends javax.swing.JFrame {

    /**
     * Creates new form mainjframe
     */
    public mainjframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderbuttongroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Userprofile = new javax.swing.JLabel();
        firstNametextfield = new javax.swing.JTextField();
        Firstname = new javax.swing.JLabel();
        Lastname = new javax.swing.JLabel();
        lastNametextfield = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        maleradiobutton = new javax.swing.JRadioButton();
        femaleradiobutton = new javax.swing.JRadioButton();
        otherradiobutton = new javax.swing.JRadioButton();
        age = new javax.swing.JLabel();
        agetextfield = new javax.swing.JTextField();
        phonenumber = new javax.swing.JLabel();
        phonetextfieldbutton = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailtextfieldbutton = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        Uploadphoto = new javax.swing.JLabel();
        selectphotofield = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        Userprofile.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Userprofile.setText("Create  a profile");

        firstNametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNametextfieldActionPerformed(evt);
            }
        });

        Firstname.setText("First Name");

        Lastname.setText("Last Name");

        gender.setText("Gender");

        genderbuttongroup.add(maleradiobutton);
        maleradiobutton.setText("Male");

        genderbuttongroup.add(femaleradiobutton);
        femaleradiobutton.setText("Female");

        genderbuttongroup.add(otherradiobutton);
        otherradiobutton.setText("Other");

        age.setText("Age");

        phonenumber.setText("Phone Number");

        phonetextfieldbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetextfieldbuttonActionPerformed(evt);
            }
        });

        email.setText("Email");

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        Uploadphoto.setText("Upload Photo");

        selectphotofield.setText("Select Photo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitbutton)
                .addGap(265, 265, 265))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Uploadphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherradiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleradiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleradiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lastNametextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(firstNametextfield, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phonetextfieldbutton, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(selectphotofield, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Firstname))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lastname)
                    .addComponent(lastNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender)
                    .addComponent(maleradiobutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(femaleradiobutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otherradiobutton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(age)
                    .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(phonenumber))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phonetextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uploadphoto)
                    .addComponent(selectphotofield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(submitbutton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonetextfieldbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetextfieldbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetextfieldbuttonActionPerformed

    private void firstNametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNametextfieldActionPerformed
 
        
    }//GEN-LAST:event_firstNametextfieldActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
        try {
        String name;
        String lastname;
        String gender = "";
        int age;
        int phonenumber;
        String email = "";
        File photoFile = null;
        
        name = this.firstNametextfield.getText().trim();
        lastname = this.lastNametextfield.getText().trim();
        
        if (maleradiobutton.isSelected()){
            gender = "Male";
        } else if (femaleradiobutton.isSelected()){
            gender = "Female";
        } else if (otherradiobutton.isSelected()) {
            gender = "Other";
        }
        
        age = Integer.parseInt(this.agetextfield.getText().trim());
        phonenumber = Integer.parseInt(this.phonetextfieldbutton.getText().trim());
        email = this.emailtextfieldbutton.getText().trim();
        
        System.out.println(name);
        System.out.println(lastname);
        System.out.println(gender);
        System.out.println(age);
        System.out.println(phonenumber);
        System.out.println(email);
        
        String photoPath = this.selectphotofield.getText().trim();
        if (photoPath.isEmpty()) {
            photoFile = null;
        } else {
            photoFile = new File(photoPath);
        }
        
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your first name", "Oops", HEIGHT);
        } else if (lastname.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your last name", "Oops", HEIGHT);
        } else if (gender.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Please select your gender", "Oops", HEIGHT);
        } else if (agetextfield.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your age", "Oops", HEIGHT);
        } else if (phonetextfieldbutton.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your phone number", "Oops", HEIGHT);
        } else if (email.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter your email", "Oops", HEIGHT);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Welcome "  + name +  " " + lastname, "Success!", HEIGHT);
        }    
    } catch (NullPointerException ne) {
        JOptionPane.showMessageDialog(rootPane, "Please enter details above", "Oops!", HEIGHT);
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(rootPane, "Please enter valid number for age and phone", "Oops", HEIGHT);
    } catch (HeadlessException ex) {
        JOptionPane.showMessageDialog(rootPane, "An expected error occured:" + ex.getMessage(), "Error", HEIGHT);
    }//GEN-LAST:event_submitbuttonActionPerformed
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainjframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Firstname;
    private javax.swing.JLabel Lastname;
    private javax.swing.JLabel Uploadphoto;
    private javax.swing.JLabel Userprofile;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtextfieldbutton;
    private javax.swing.JRadioButton femaleradiobutton;
    private javax.swing.JTextField firstNametextfield;
    private javax.swing.JLabel gender;
    private javax.swing.ButtonGroup genderbuttongroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNametextfield;
    private javax.swing.JRadioButton maleradiobutton;
    private javax.swing.JRadioButton otherradiobutton;
    private javax.swing.JLabel phonenumber;
    private javax.swing.JTextField phonetextfieldbutton;
    private javax.swing.JButton selectphotofield;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
