/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;

/**
 *
 * @author ProBook
 */
public class FormJPanel extends javax.swing.JPanel {
    JPanel bottomPanel;
    ImageIcon imagePicture;
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }
    
    public FormJPanel(JPanel bottomPanel){
       initComponents(); 
       this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Userprofile = new javax.swing.JLabel();
        Firstname = new javax.swing.JLabel();
        Lastname = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        phonenumber = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        hobbiesLabel = new javax.swing.JLabel();
        firstNametextfield = new javax.swing.JTextField();
        lastNametextfield = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        agetextfield = new javax.swing.JTextField();
        phonetextfieldbutton = new javax.swing.JTextField();
        emailtextfieldbutton = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbiesTextArea = new javax.swing.JTextArea();
        submitbutton = new javax.swing.JButton();
        uploadImageLabel = new javax.swing.JLabel();
        imageButton = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        Userprofile.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Userprofile.setText("Create  a profile");

        Firstname.setText("First Name");

        Lastname.setText("Last Name");

        gender.setText("Gender");

        age.setText("Age");

        phonenumber.setText("Phone Number");

        email.setText("Email");

        hobbiesLabel.setText("Hobbies");

        firstNametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNametextfieldActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);

        phonetextfieldbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetextfieldbuttonActionPerformed(evt);
            }
        });

        hobbiesTextArea.setColumns(20);
        hobbiesTextArea.setRows(5);
        jScrollPane1.setViewportView(hobbiesTextArea);

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        uploadImageLabel.setText("Upload Photo");

        imageButton.setText("Select Image");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitbutton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agetextfield)
                    .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNametextfield)
                    .addComponent(firstNametextfield)
                    .addComponent(phonetextfieldbutton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Firstname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lastname)
                    .addComponent(lastNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonetextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbiesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageButton)
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadImageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitbutton)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNametextfieldActionPerformed

    }//GEN-LAST:event_firstNametextfieldActionPerformed

    private void phonetextfieldbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetextfieldbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetextfieldbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            User userObject = new User();

            //name = this.firstNametextfield.getText().trim();
            userObject.setName(this.firstNametextfield.getText().trim());
            //lastname = this.lastNametextfield.getText().trim();
            userObject.setLastname(this.lastNametextfield.getText().trim());
            //gender = this.genderComboBox.getSelectedItem().toString();
            userObject.setGender(this.genderComboBox.getSelectedItem().toString());
            //hobbies = this.hobbiesTextArea.getText();
            userObject.setHobbies(this.hobbiesTextArea.getText());

            //age = Integer.parseInt(this.agetextfield.getText().trim());
            userObject.setAge(Integer.parseInt(this.agetextfield.getText().trim()));
            //phonenumber = Integer.parseInt(this.phonetextfieldbutton.getText().trim());
            userObject.setPhonenumber(this.phonetextfieldbutton.getText().trim());
            //email = this.emailtextfieldbutton.getText().trim();
            userObject.setEmail(this.emailtextfieldbutton.getText().trim());
            userObject.setImagePicture(imagePicture);

            System.out.println(userObject.getName());
            System.out.println(userObject.getLastname());
            System.out.println(userObject.getGender());
            System.out.println(userObject.getAge());
            System.out.println(userObject.getPhonenumber());
            System.out.println(userObject.getEmail());
            System.out.println(userObject.getHobbies());
            System.out.println(userObject);

            if (userObject.getName().isBlank()) {
                JOptionPane.showMessageDialog(this, "Please enter your first name", "Oops", HEIGHT);
            } else if (userObject.getLastname().isBlank()){
                JOptionPane.showMessageDialog(this, "Please enter your last name", "Oops", HEIGHT);
            } else if (userObject.getGender().isBlank()){
                JOptionPane.showMessageDialog(this, "Please select your gender", "Oops", HEIGHT);
            } else if (agetextfield.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter your age", "Oops", HEIGHT);
            } else if (phonetextfieldbutton.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter your phone number", "Oops", HEIGHT);
            } else if (userObject.getEmail().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter your email", "Oops", HEIGHT);

            } else if (userObject.getHobbies() .isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter your hobbies", "Oops", HEIGHT);
            } else {
                JOptionPane.showMessageDialog(this,userObject, "Success!",HEIGHT, this.imagePicture);
                //Naviagte to view J Panel
                ViewJPanel viewJPanelObject = new ViewJPanel(userObject); 
                this.bottomPanel.add(viewJPanelObject);
                CardLayout layout = (CardLayout) this.bottomPanel.getLayout();
                layout.next(bottomPanel);
            }
      } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(this, "Please enter details above", "Oops!", HEIGHT);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Please enter valid number for age and phone", "Oops", HEIGHT);
      } catch (HeadlessException ex) {
          JOptionPane.showMessageDialog(this, "An expected error occured:" + ex.getMessage(), "Error", HEIGHT);
      }
    }//GEN-LAST:event_submitbuttonActionPerformed
    
    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
        try {
        BufferedImage img = ImageIO.read(file.getSelectedFile());
        Image edited_image = img.getScaledInstance(60, 80,
        Image.SCALE_SMOOTH);
        if (edited_image != null) {
            this.imgLabel.setIcon(new ImageIcon(edited_image));
            this.imagePicture = new ImageIcon(edited_image);
        //this.userInfo.setPic(new ImageIcon(edited_image));
        }
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Please upload image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_imageButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Firstname;
    private javax.swing.JLabel Lastname;
    private javax.swing.JLabel Userprofile;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtextfieldbutton;
    private javax.swing.JTextField firstNametextfield;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JTextArea hobbiesTextArea;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNametextfield;
    private javax.swing.JLabel phonenumber;
    private javax.swing.JTextField phonetextfieldbutton;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel uploadImageLabel;
    // End of variables declaration//GEN-END:variables
}
