/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.User;

/**
 *
 * @author ProBook
 */
public class ViewJPanel extends javax.swing.JPanel {
    private User userObject;

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel() {
        initComponents();
    }
    public ViewJPanel(User userObject){
        initComponents();
        this.userObject = userObject;
        setALLFields();
        
    }
    public void setALLFields(){
        this.firstNametextfield.setText(userObject.getName());
        this.genderComboBox.setSelectedItem(userObject.getGender());
        this.lastNametextfield.setText(userObject.getLastname());
        this.emailtextfieldbutton.setText(userObject.getEmail());
        this.agetextfield.setText(String.valueOf(userObject.getAge()));
        this.phonetextfieldbutton.setText(String.valueOf(userObject.getPhonenumber()));
        this.hobbiesTextArea.setText(userObject.getHobbies());
        this.imagePhotoLabel.setIcon(userObject.getImagePicture());
        //String.valueOf(userObject.getAge());
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Userprofile = new javax.swing.JLabel();
        firstNametextfield = new javax.swing.JTextField();
        lastNametextfield = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        Firstname = new javax.swing.JLabel();
        Lastname = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        agetextfield = new javax.swing.JTextField();
        phonetextfieldbutton = new javax.swing.JTextField();
        phonenumber = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        emailtextfieldbutton = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbiesTextArea = new javax.swing.JTextArea();
        hobbiesLabel = new javax.swing.JLabel();
        imagePhotoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 153));

        Userprofile.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Userprofile.setText("Create  a profile");

        firstNametextfield.setEnabled(false);
        firstNametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNametextfieldActionPerformed(evt);
            }
        });

        lastNametextfield.setEnabled(false);

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);
        genderComboBox.setEnabled(false);

        Firstname.setText("First Name");

        Lastname.setText("Last Name");

        gender.setText("Gender");

        age.setText("Age");

        agetextfield.setEnabled(false);

        phonetextfieldbutton.setEnabled(false);
        phonetextfieldbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetextfieldbuttonActionPerformed(evt);
            }
        });

        phonenumber.setText("Phone Number");

        email.setText("Email");

        emailtextfieldbutton.setEnabled(false);

        hobbiesTextArea.setColumns(20);
        hobbiesTextArea.setRows(5);
        hobbiesTextArea.setEnabled(false);
        jScrollPane1.setViewportView(hobbiesTextArea);

        hobbiesLabel.setText("Hobbies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hobbiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonetextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagePhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGap(114, 114, 114))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(412, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Userprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(firstNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phonetextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailtextfieldbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hobbiesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(Firstname)
                    .addGap(18, 18, 18)
                    .addComponent(Lastname)
                    .addGap(18, 18, 18)
                    .addComponent(gender)
                    .addGap(30, 30, 30)
                    .addComponent(age)
                    .addGap(18, 18, 18)
                    .addComponent(phonenumber)
                    .addGap(32, 32, 32)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(199, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNametextfieldActionPerformed

    }//GEN-LAST:event_firstNametextfieldActionPerformed

    private void phonetextfieldbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetextfieldbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetextfieldbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Firstname;
    private javax.swing.JLabel Lastname;
    private javax.swing.JLabel Userprofile;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtextfieldbutton;
    private javax.swing.JTextField firstNametextfield;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JTextArea hobbiesTextArea;
    private javax.swing.JLabel imagePhotoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNametextfield;
    private javax.swing.JLabel phonenumber;
    private javax.swing.JTextField phonetextfieldbutton;
    // End of variables declaration//GEN-END:variables
}
